version: '3.7'
services:
  web:
    build:
       context: ./project
       dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONTAINER=web
  timescale:
    image: timescale/timescaledb:latest-pg10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/:/etc/prometheus/
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3060:3000
    
volumes:
  db_data:
